Repository ITech-Fixers/vide-grenier-en-ligne, pull requests merged in 2024-07, with the labels that each got.

#40 Fix: nom du paramètre attendu pour le tri par date des articles
  App/Models/Articles.php
Labels: fix, back

#45 Implémentation de swagger pour l'API
  App/Controllers/Api.php
  Dockerfile
  composer.json
  composer.lock
  public/swagger-ui/favicon-16x16.png
  public/swagger-ui/favicon-32x32.png
  public/swagger-ui/index.css
  public/swagger-ui/index.html
  public/swagger-ui/oauth2-redirect.html
  public/swagger-ui/swagger-initializer.js
  public/swagger-ui/swagger-ui-bundle.js
  public/swagger-ui/swagger-ui-bundle.js.map
  public/swagger-ui/swagger-ui-es-bundle-core.js
  public/swagger-ui/swagger-ui-es-bundle-core.js.map
  public/swagger-ui/swagger-ui-es-bundle.js
  public/swagger-ui/swagger-ui-es-bundle.js.map
  public/swagger-ui/swagger-ui-standalone-preset.js
  public/swagger-ui/swagger-ui-standalone-preset.js.map
  public/swagger-ui/swagger-ui.css
  public/swagger-ui/swagger-ui.css.map
  public/swagger-ui/swagger-ui.js
  public/swagger-ui/swagger-ui.js.map
  public/swagger-ui/swagger.yaml
Labels: documentation

#47 Fix: mise à jour du fichier de configuration openapi versionné
  App/Controllers/Api.php
  public/swagger-ui/swagger.yaml
Labels: documentation, fix

#51 Centrage des formulaires contact + ajout d'article
  App/Views/Product/Add.html
  App/Views/Product/Contact.html
Labels: fix, front

#50 Maj de la récuperation des articles d'un utilisateur dans l'espace compte via un call AJAX
  App/Controllers/Api.php
  App/Controllers/User.php
  App/Models/Articles.php
  App/Views/User/account.html
Labels: fix, feature

#46 Fix: icônes tri des articles
  App/Views/Home/index.html
Labels: fix, front

#52 Feature: Articles "autour de moi"
  App/Controllers/Api.php
  App/Models/Articles.php
  App/Views/Home/index.html
  App/Views/base.html
  public/swagger-ui/swagger.yaml
Labels: feature

#55 Feature: Recherche des articles
  App/Controllers/Api.php
  App/Models/Articles.php
  App/Views/Home/index.html
  App/Views/Product/Add.html
  App/Views/Product/Contact.html
  App/Views/base.html
  public/swagger-ui/swagger.yaml
Labels: feature

#56 Add statistics page
  App/Controllers/Api.php
  App/Controllers/Statistics.php
  App/Controllers/User.php
  App/Models/Articles.php
  App/Models/User.php
  App/Views/Admin/Statistics.html
  App/Views/base.html
  Core/Controller.php
  public/index.php
  public/storage/46.png
  public/style/main.css
  public/style/main.css.map
  public/swagger-ui/swagger.yaml
  style/_custom.scss
  style/_header.scss
Labels: dev, css, back, front, feature

#62 Typage et ajout des dockblocs manquants du back
  App/Controllers/Api.php
  App/Controllers/Home.php
  App/Controllers/Statistics.php
  App/Controllers/User.php
  App/Models/Articles.php
  App/Models/Cities.php
  App/Models/User.php
  App/Service/Validation/ArticleAdd.php
  App/Service/Validation/ContactMessage.php
  App/Service/Validation/UserRegister.php
  App/Utility/Flash.php
  App/Utility/Hash.php
  App/Utility/Upload.php
  App/Views/Admin/Statistics.html
  Core/Controller.php
  Core/Model.php
  Core/Router.php
  public/index.php
Labels: fix, back

#65 Fix Dockerfile
  Dockerfile
  entrypoint.sh
Labels: bug, fix, config

#68 Fix: Gestion des pages 404/500
  App/Config.php
  App/Views/404.html
  App/Views/500.html
  Core/Router.php
  public/index.php
Labels: fix, back

#73 Fix config Docker
  Dockerfile
  Makefile
  docker-compose.yml
  entrypoint.sh
Labels: infra, fix

#72 MAJ du mail
  App/Config.php
  App/Controllers/Product.php
  App/MailTemplate/message_mail.html
  App/Service/Validation/ContactMessage.php
  App/Utility/Mailer.php
  App/Views/Product/Contact.html
  Core/Controller.php
Labels: fix, back, front, config

#75 Nettoyage et formatage des templates HTML
  App/Views/Admin/Statistics.html
  App/Views/Home/index.html
  App/Views/Product/Add.html
  App/Views/Product/Contact.html
  App/Views/Product/Show.html
  App/Views/User/account.html
  App/Views/User/login.html
  App/Views/User/other.html
  App/Views/User/register.html
  App/Views/base.html
Labels: enhancement, front

#78 Evol: Ajout support .env
  .env.example
  .gitignore
  App/Config.php
  App/Controllers/Product.php
  Core/Error.php
  Core/Model.php
  README.md
  composer.json
  composer.lock
  public/index.php
Labels: enhancement, config

#77 Fix: Supression des secrets utilisateurs dans les réponses SQL
  App/Models/Articles.php
  App/Views/Home/index.html
Labels: fix, back

#76 Fix: Gestion des erreurs à l'upload de ficher
  App/Controllers/Product.php
  App/Exception/FileFormatException.php
  App/Utility/Upload.php
  App/Views/Product/Add.html
Labels: fix, back

#80 Evol: Ajout d'une classe Kernel pour centraliser la config et le setup de l'Application
  Core/Controller.php
  Core/Error.php
  Core/Kernel.php
  Core/Model.php
  Core/Router.php
  Core/View.php
  public/index.php
Labels: enhancement, back
