Repository ITech-Fixers/vide-grenier-en-ligne, pull requests merged in 2024-05, with the labels that each got.

#3 Fix : DB Config
  App/Config.php
  App/Views/User/register.html
  Core/Model.php
  Dockerfile
Labels: fix, db

#4 FIX CSS pour la page d'accueil et login et register
  App/Views/User/login.html
  App/Views/base.html
  public/bootstrap/css/bootstrap-grid.css
  public/bootstrap/css/bootstrap-grid.css.map
  public/bootstrap/css/bootstrap-grid.min.css
  public/bootstrap/css/bootstrap-grid.min.css.map
  public/bootstrap/css/bootstrap-grid.rtl.css
  public/bootstrap/css/bootstrap-grid.rtl.css.map
  public/bootstrap/css/bootstrap-grid.rtl.min.css
  public/bootstrap/css/bootstrap-grid.rtl.min.css.map
  public/bootstrap/css/bootstrap-reboot.css
  public/bootstrap/css/bootstrap-reboot.css.map
  public/bootstrap/css/bootstrap-reboot.min.css
  public/bootstrap/css/bootstrap-reboot.min.css.map
  public/bootstrap/css/bootstrap-reboot.rtl.css
  public/bootstrap/css/bootstrap-reboot.rtl.css.map
  public/bootstrap/css/bootstrap-reboot.rtl.min.css
  public/bootstrap/css/bootstrap-reboot.rtl.min.css.map
  public/bootstrap/css/bootstrap-utilities.css
  public/bootstrap/css/bootstrap-utilities.css.map
  public/bootstrap/css/bootstrap-utilities.min.css
  public/bootstrap/css/bootstrap-utilities.min.css.map
  public/bootstrap/css/bootstrap-utilities.rtl.css
  public/bootstrap/css/bootstrap-utilities.rtl.css.map
  public/bootstrap/css/bootstrap-utilities.rtl.min.css
  public/bootstrap/css/bootstrap-utilities.rtl.min.css.map
  public/bootstrap/css/bootstrap.css.map
  public/bootstrap/css/bootstrap.min.css.map
  public/bootstrap/css/bootstrap.rtl.css
  public/bootstrap/css/bootstrap.rtl.css.map
  public/bootstrap/css/bootstrap.rtl.min.css
  public/bootstrap/css/bootstrap.rtl.min.css.map
  public/bootstrap/js/bootstrap.bundle.js
  public/bootstrap/js/bootstrap.bundle.js.map
  public/bootstrap/js/bootstrap.bundle.min.js.map
  public/bootstrap/js/bootstrap.esm.js
  public/bootstrap/js/bootstrap.esm.js.map
  public/bootstrap/js/bootstrap.esm.min.js
  public/bootstrap/js/bootstrap.esm.min.js.map
  public/bootstrap/js/bootstrap.js.map
  public/bootstrap/js/bootstrap.min.js.map
  public/images/login-bg.png
  public/style/main.css
  public/style/main.css.map
  style/_account.scss
  style/_content.scss
Labels: bug, dev, fix, css

#6 Fix : Register & Login
  App/Controllers/User.php
  App/Models/User.php
  App/Models/UserRegister.php
  App/Utility/Flash.php
  App/Views/User/login.html
  App/Views/User/register.html
  Core/Error.php
  Core/View.php
Labels: fix, auth

#18 Ajout du système de toast sur le layout
  App/Views/User/login.html
  App/Views/User/register.html
  App/Views/base.html
  public/style/main.css
  public/style/main.css.map
  style/_general.scss
Labels: dev, css, front, feature

#17 Ajout du Favicon
  App/Views/base.html
  public/favicon/android-chrome-192x192.png
  public/favicon/android-chrome-512x512.png
  public/favicon/apple-touch-icon.png
  public/favicon/browserconfig.xml
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon.ico
  public/favicon/mstile-150x150.png
  public/favicon/safari-pinned-tab.svg
  public/favicon/site.webmanifest
Labels: fix, front, feature

#22 Fix : Gestion des exceptions au login et register
  App/Controllers/User.php
  App/Exception/UserNotFoundException.php
  App/Exception/ValidationException.php
  App/Views/User/login.html
  App/Views/User/register.html
Labels: fix, auth, back

#24 Fix systeme de séléction des villes
  App/Models/Cities.php
  App/Views/Product/Add.html
  App/Views/base.html
Labels: dev, fix, back, front
